#!/usr/bin/env bash
################################################################################
PROGRAM=$(basename $0)
read -r -d '' USAGE << EOM
Create release sources based on existing one.

Usage:
  $PROGRAM -r VERSION
  $PROGRAM [--help]

Options:
  -r VERSION            Specify rust version to create.
  -h, --help            Print help message.
EOM


################################################################################
function show_usage_and_exit_with_code {
  echo "$USAGE"
  exit $1
}


function process_params {
  if [[ "$1" = "--" ]]; then
    show_usage_and_exit_with_code 1
  fi

  while true; do
    case "$1" in
        -r)
            RELEASE_VERSION="$2"
            shift 2
            ;;
        -h|--help)
            show_usage_and_exit_with_code 0
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error"
            exit 3
            ;;
    esac
  done
}


function validate_rust_release_is_specified {
  if [[ "${RELEASE_VERSION}x" = "x" ]]; then
    echo "Error: Rust release is not specified"
    exit 1
  fi
}

function validate_input {
  validate_rust_release_is_specified
}
################################################################################
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "I’m sorry, `getopt --test` failed in this environment."
    exit 1
fi

SHORT="r:h"
LONG="help"
PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")


if [[ $? -ne 0 ]]; then
    # e.g. $? == 1
    #  then getopt has complained about wrong arguments to stdout
    exit 2
fi

# Flat out parsed params into list of arguments
eval set -- "$PARSED"
################################################################################

process_params $@
validate_input
mkdir -p $RELEASE_VERSION
cp -R 1.16.0/* $RELEASE_VERSION/

SEMVER_PATTERN="[0-9]+\.[0-9]+\.[0-9]+"
ROOT_DIR=$(pwd)

pushd 1.16.0 > /dev/null
for distro_family in $(ls); do
  pushd $distro_family > /dev/null
  for distro_release in $(ls); do
    TARGET_FILE="${ROOT_DIR}/${RELEASE_VERSION}/${distro_family}/${distro_release}/Dockerfile"
    sed -i -r \
        -e "s/Rust ${SEMVER_PATTERN}/Rust ${RELEASE_VERSION}/g" \
        -e "s/rust:${SEMVER_PATTERN}/rust:${RELEASE_VERSION}/g" \
        -e "s/RUST_VERSION=${SEMVER_PATTERN}/RUST_VERSION=${RELEASE_VERSION}/g" \
        -e "s/version=\S*/version=\"$(date +"%F")\"/g" \
        ${TARGET_FILE}

    TARGET_FILE="${ROOT_DIR}/${RELEASE_VERSION}/${distro_family}/${distro_release}/recipes/docker-compose.yml"
    sed -i -r \
        -e "s/rust:${SEMVER_PATTERN}/rust:${RELEASE_VERSION}/g" \
        ${TARGET_FILE}
  done
  popd > /dev/null
done
popd > /dev/null
