version: '2'
services:
  dev:
    image: eleidan/rust:1.18.0-xenial
    environment:
      - CARGO_HOME=/home/phantom/app/.cargo
    volumes:
      - .:/home/phantom/app
      - .docker/.bash_history:/home/phantom/.bash_history
