version: '2'

volumes:
  bash-history:
  cargo-registry:

services:
  dev:
    build: .
    image: rust_project
    user: phantom
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
      - cargo-registry:/home/phantom/.cargo/registry
