version: '2'

volumes:
  bash-history:
  cargo-registry:

services:
  dev:
    image: eleidan/rust:beta-ubuntu-16.04
    user: phantom
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
      - cargo-registry:/home/phantom/.cargo/registry
